server:
  port: 443
  ssl:
    key-store: keystore.p12
    key-store-password: Root@123
    keyStoreType: PKCS12
    keyAlias: tomcat
spring:
  application:
    name: PERSONAL-BROKER
  datasource:
    url: jdbc:mysql://localhost:3306/broker?autoReconnect=true&useSSL=false
    username: root
    password: $Root123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      connection-timeout: 30000    # 30 seconds
      idle-timeout: 36000000       # 10 hours (or set to 0 to disable)
      max-lifetime: 36000000       # 10 hours
      pool-name: HikariPool-1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true